USE BD_MATRICULA_KENDALL
GO
--CRUD DE ESTUDIANTES 

--INSERTAR 
GO
CREATE OR ALTER PROCEDURE INSERTAR_ESTUDIANTE(@CARNET VARCHAR(10),
											  @ID_ESTUDIANTE INT,
									          @NOMBRE_ESTUDIANTE VARCHAR(30),
								           	  @PRIMER_APELLIDO_E VARCHAR(30),
									          @SEGUNDO_APELLIDO_E VARCHAR(30),
									          @CORREO_ESTUDIANTE VARCHAR(150),
									          @NUMERO_TELEFONO VARCHAR(30),
									          @FECHA_INGRESO DATE)
AS
	BEGIN 
		INSERT INTO ESTUDIANTES(CARNET,NOMBRE_ESTUDIANTE,PRIMER_APELLIDO_E,SEGUNDO_APELLIDO_E,CORREO_ESTUDIANTE,NUMERO_TELEFONO,FECHA_INGRESO)
			VALUES (@CARNET,@NOMBRE_ESTUDIANTE,@PRIMER_APELLIDO_E,@SEGUNDO_APELLIDO_E,@CORREO_ESTUDIANTE,@NUMERO_TELEFONO,@FECHA_INGRESO)
    
	SET  @ID_ESTUDIANTE=IDENT_CURRENT('ESTUDIANTES')
	END

GO


--LEER 
CREATE OR ALTER PROCEDURE LEER_ESTUDIANTE(@CARNET VARCHAR(10))

AS
BEGIN
	SELECT * FROM ESTUDIANTES WHERE CARNET = @CARNET
END


GO

--ACTUALIZAR 
CREATE OR ALTER PROCEDURE ACTUALIZAR_ESTUDIANTE(@CARNET VARCHAR(10),
											    @NOMBRE_ESTUDIANTE VARCHAR(30),
											    @PRIMER_APELLIDO_E VARCHAR(30),
											    @SEGUNDO_APELLIDO_E VARCHAR(30),
											    @CORREO_ESTUDIANTE VARCHAR(150),
											    @NUMERO_TELEFONO VARCHAR(30),
										   	    @FECHA_INGRESO DATE)

AS
BEGIN
UPDATE ESTUDIANTES SET CARNET = @CARNET, NOMBRE_ESTUDIANTE = @NOMBRE_ESTUDIANTE, PRIMER_APELLIDO_E=@PRIMER_APELLIDO_E,
					   SEGUNDO_APELLIDO_E=@SEGUNDO_APELLIDO_E,CORREO_ESTUDIANTE=@CORREO_ESTUDIANTE, NUMERO_TELEFONO=@NUMERO_TELEFONO,
					   FECHA_INGRESO=@FECHA_INGRESO WHERE CARNET = @CARNET
END

GO


--BORRAR 
CREATE OR ALTER PROCEDURE ELIMINAR_ESTUDIANTE(@CARNET VARCHAR(10))

AS
BEGIN
	DELETE FROM ESTUDIANTES WHERE CARNET = @CARNET
END

GO

--CRUD LABORATORIO 
--INSERTAR 
GO
CREATE OR ALTER PROCEDURE INSERTAR_LABORATORIO(@COD_LABORATORIO INT,
											   @UBICACION_LABORATORIO VARCHAR(50))
AS
	BEGIN 
		INSERT INTO LABORATORIOS(UBICACION_LABORATORIO)
			VALUES (@UBICACION_LABORATORIO)
    
	SET  @COD_LABORATORIO=IDENT_CURRENT('LABORATORIOS')
	END

GO


--LEER 
CREATE OR ALTER PROCEDURE LEER_LABORATORIO(@COD_LABORATORIO VARCHAR(10))

AS
BEGIN
	SELECT * FROM LABORATORIOS WHERE COD_LABORATORIO = @COD_LABORATORIO
END

GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_LABORATORIO(@COD_LABORATORIO INT,
												 @UBICACION_LABORATORIO VARCHAR(10))

AS
BEGIN
	UPDATE LABORATORIOS SET UBICACION_LABORATORIO=@UBICACION_LABORATORIO WHERE COD_LABORATORIO = @COD_LABORATORIO
END

GO

--BORRAR
CREATE PROCEDURE ELIMINAR_LABORATORIO(@COD_LABORATORIO INT)

AS
BEGIN
	DELETE FROM LABORATORIOS WHERE COD_LABORATORIO = @COD_LABORATORIO
END

--CRUD PROFESORES 
--INSERTAR
GO
CREATE OR ALTER PROCEDURE INSERTAR_PROFESOR(@ID_PROFESOR INT,
											@COD_PROFESOR INT,
											@NOMBRE_PROFESOR VARCHAR(30),
											@PRIMER_APELLIDO_P VARCHAR(30),
											@SEGUNDO_APELLIDO_P VARCHAR(30),
											@CORREO_PROFESOR VARCHAR(150),
											@NUMERO_TELEFONO_PROFESOR VARCHAR(30))

AS
BEGIN
	INSERT INTO PROFESORES (ID_PROFESOR, NOMBRE_PROFESOR, PRIMER_APELLIDO_P, SEGUNDO_APELLIDO_P, CORREO_PROFESOR, NUMERO_TELEFONO_PROFESOR)
		VALUES (@ID_PROFESOR, @NOMBRE_PROFESOR, @PRIMER_APELLIDO_P, @SEGUNDO_APELLIDO_P, @CORREO_PROFESOR, @NUMERO_TELEFONO_PROFESOR)

		SET  @COD_PROFESOR=IDENT_CURRENT('PROFESORES')
END

GO

--LEER 
CREATE OR ALTER PROCEDURE LEER_PROFESOR(@COD_PROFESOR int)
AS
BEGIN
	SELECT * FROM PROFESORES WHERE COD_PROFESOR = @COD_PROFESOR
END
GO

--ACTUALIZAR 
CREATE OR ALTER PROCEDURE ACTUALIZAR_PROFESOR(@COD_PROFESOR INT,
											  @ID_PROFESOR INT,
											  @NOMBRE_PROFESOR VARCHAR(30),
											  @PRIMER_APELLIDO_P VARCHAR(30),
										      @SEGUNDO_APELLIDO_P VARCHAR(30),
                                              @CORREO_PROFESOR VARCHAR(150),
                                              @NUMERO_TELEFONO_PROFESOR VARCHAR(30),
                                              @ESTADO_P VARCHAR(30),
                                              @BORRADO BIT)

AS
BEGIN
UPDATE PROFESORES 
SET ID_PROFESOR = @ID_PROFESOR, NOMBRE_PROFESOR = @NOMBRE_PROFESOR, PRIMER_APELLIDO_P = @PRIMER_APELLIDO_P, 
SEGUNDO_APELLIDO_P = @SEGUNDO_APELLIDO_P, CORREO_PROFESOR = @CORREO_PROFESOR, NUMERO_TELEFONO_PROFESOR = @NUMERO_TELEFONO_PROFESOR, 
ESTADO_P = @ESTADO_P, BORRADO = @BORRADO WHERE COD_PROFESOR = @COD_PROFESOR
END

GO

--ELIMINAR 
CREATE PROCEDURE ELIMINAR_PROFESOR(@COD_PROFESOR INT)
AS
BEGIN
	DELETE FROM PROFESORES WHERE COD_PROFESOR = @COD_PROFESOR
END

GO


--CRUD MATERIAS
--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_MATERIA(@COD_MATERIA VARCHAR(30),
								  @NOMBRE_MATERIA VARCHAR(150),
								  @CREDITOS_C INT,
								  @DURACION INT,
							      @COSTO DECIMAL(10,2))
AS
BEGIN
	INSERT INTO MATERIAS (COD_MATERIA, NOMBRE_MATERIA, CEDITOS_C, DURACION, COSTO)
		VALUES (@COD_MATERIA, @NOMBRE_MATERIA, @CREDITOS_C, @DURACION, @COSTO)
END

GO


--LEER
CREATE OR ALTER PROCEDURE LEER_MATERIA(@COD_MATERIA VARCHAR(30))
AS
BEGIN
	SELECT * FROM MATERIAS WHERE COD_MATERIA = @COD_MATERIA
END

GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_MATERIA(@COD_MATERIA VARCHAR(30),
									@NOMBRE_MATERIA VARCHAR(150),
									@CREDITOS_C INT,
									@DURACION INT,
									@COSTO DECIMAL(10,2),
									@BORRADO_CARRERA BIT)

AS
BEGIN
	UPDATE MATERIAS 
	SET NOMBRE_MATERIA = @NOMBRE_MATERIA, CEDITOS_C = @CREDITOS_C, DURACION = @DURACION, 
	COSTO = @COSTO, BORRADO_CARRERA = @BORRADO_CARRERA WHERE COD_MATERIA = @COD_MATERIA
END

GO

--BORRAR 
CREATE OR ALTER PROCEDURE ELIMINAR_MATERIA(@COD_MATERIA VARCHAR(30))
AS
BEGIN
DELETE FROM MATERIAS WHERE COD_MATERIA = @COD_MATERIA
END

GO

--CRUD CARRERAS

--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_CARRERA(@COD_CARRERA VARCHAR(30),
							  @NOMBRE_CARRERA VARCHAR(150),
							  @CREDITOS_M INT,
							  @GRADO VARCHAR(30))
AS
BEGIN
	INSERT INTO CARRERAS (COD_CARRERA, NOMBRE_CARRERA, CEDITOS_M, GRADO)
		VALUES (@COD_CARRERA, @NOMBRE_CARRERA, @CREDITOS_M, @GRADO)
END

GO

--LEER 
CREATE OR ALTER PROCEDURE LEER_CARRERA(@COD_CARRERA VARCHAR(30))
AS
BEGIN
	SELECT * FROM CARRERAS WHERE COD_CARRERA = @COD_CARRERA
END

GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_CARRERA(@COD_CARRERA VARCHAR(30),
											 @NOMBRE_CARRERA VARCHAR(150),
											 @CREDITOS_M INT,
											 @GRADO VARCHAR(30),
											 @BORRADO_MATERIA BIT)
AS
BEGIN
	UPDATE CARRERAS 
	SET NOMBRE_CARRERA = @NOMBRE_CARRERA, CEDITOS_M = @CREDITOS_M, GRADO = @GRADO, 
	BORRADO_MATERIA = @BORRADO_MATERIA WHERE COD_CARRERA = @COD_CARRERA
END

GO

--BORRAR
CREATE OR ALTER PROCEDURE ELIMINAR_CARRERA(@COD_CARRERA varchar(30))
AS
BEGIN
	DELETE FROM CARRERAS WHERE COD_CARRERA = @COD_CARRERA
END

GO

--CRUD MATERIAS_CARRERAS
--INSERTAR 
CREATE OR ALTER PROCEDURE INSERTAR_MATERIA_CARRERA(@COD_CARRERA VARCHAR(30),
												   @COD_MATERIA VARCHAR(30))

AS
BEGIN
	INSERT INTO MATERIAS_CARRERAS (COD_CARRERA, COD_MATERIA)
	VALUES (@COD_CARRERA, @COD_MATERIA)
END
GO


--LEER 
CREATE OR ALTER  PROCEDURE LEER_MATERIA_CARRERA(@COD_MATERIA_CARRERA INT)

AS
BEGIN
	SELECT * FROM MATERIAS_CARRERAS WHERE COD_MATERIA_CARRERA = @COD_MATERIA_CARRERA
END

GO

--ACTUALIZAR 
CREATE OR ALTER PROCEDURE ACTUALIZAR_MATERIA_CARRERA(@COD_MATERIA_CARRERA INT,
										    @COD_CARRERA VARCHAR(30),
									  	    @COD_MATERIA VARCHAR(30),
										    @BORRADO_MATERIA_CARRERA BIT)
AS
BEGIN
	UPDATE MATERIAS_CARRERAS 
	SET COD_CARRERA = @COD_CARRERA, COD_MATERIA = @COD_MATERIA, BORRADO_MATERIA_CARRERA = @BORRADO_MATERIA_CARRERA
	WHERE COD_MATERIA_CARRERA = @COD_MATERIA_CARRERA
END

GO


--BORRAR
CREATE OR ALTER PROCEDURE ELIMAR_MATERIA_CARRERA(@COD_MATERIA_CARRERA INT)
AS
BEGIN
	DELETE FROM MATERIAS_CARRERAS WHERE COD_MATERIA_CARRERA = @COD_MATERIA_CARRERA
END
GO


--CRUD CALIFICACION_POR_MATERIA
--INSERTAR 

CREATE OR ALTER PROCEDURE INSERTAR_CALIFICACION_POR_MATERIA(@CARNET VARCHAR(10),
												            @COD_MATERIA_CARRERA INT,
											                @PROMEDIO FLOAT)
AS
BEGIN
	INSERT INTO CALIFICACION_POR_MATERIA (CARNET, COD_MATERIA_CARRERA, PROMEDIO)
		VALUES (@CARNET, @COD_MATERIA_CARRERA, @PROMEDIO)
END

GO

--LEER 
CREATE OR ALTER PROCEDURE LEER_CALIFICACION_POR_MATERIA(@ID_CALIFICACION INT)
AS
BEGIN
	SELECT * FROM CALIFICACION_POR_MATERIA WHERE ID_CALIFICACION = @ID_CALIFICACION
END

GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_CALIFICACION_POR_MATERIA(@CARNET VARCHAR(10),
													 @COD_MATERIA_CARRERA INT,
													 @PROMEDIO FLOAT)
AS
BEGIN
	UPDATE CALIFICACION_POR_MATERIA 
	SET CARNET = @CARNET, COD_MATERIA_CARRERA = @COD_MATERIA_CARRERA, 
	PROMEDIO = @PROMEDIO WHERE CARNET = @CARNET
END

GO


--BORRAR
CREATE OR ALTER PROCEDURE ELIMINAR_CALIFICACION_POR_MATERIA(@CARNET VARCHAR(30))
AS
BEGIN
	DELETE FROM CALIFICACION_POR_MATERIA WHERE CARNET = @CARNET
END
GO


--CRUD HORARIOS

--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_HORARIO(@COD_MATERIAS_ABIERTAS INT,
										   @DIA VARCHAR(15),
									       @HORA_INICIO TIME,
										   @HORA_FINAL TIME)
AS
BEGIN
	INSERT INTO HORARIO (COD_MATERIAS_ABIERTAS, DIA, HORA_INICIO, HORA_FINAL)
		VALUES (@COD_MATERIAS_ABIERTAS, @DIA, @HORA_INICIO, @HORA_FINAL)
END

GO


--LEER
CREATE OR ALTER PROCEDURE LEER_HORARIO(@COD_MATERIAS_ABIERTAS INT,
									   @DIA VARCHAR(15),
									   @HORA_INICIO TIME,
									   @HORA_FINAL TIME)
AS
BEGIN
	SELECT * FROM HORARIO WHERE COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS 
END

GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_HORARIO(@COD_MATERIAS_ABIERTAS int,
								   @DIA varchar(15),
								   @HORA_INICIO time,
								   @HORA_FINAL time,
								   @COD_FERIADO int)
AS
BEGIN
UPDATE HORARIO 
	SET DIA = @DIA, HORA_INICIO = @HORA_INICIO, HORA_FINAL = @HORA_FINAL
	WHERE COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS 
END

GO

--BORRAR
CREATE OR ALTER PROCEDURE ELIMINAR_HORARIO(@COD_MATERIAS_ABIERTAS INT)

AS
BEGIN
DELETE FROM HORARIO WHERE COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS 
END

GO

--CRUD FERIADOS

--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_FERIADO(@DIA_FERIADO DATE,
								 @DESCRIPCION_FERIADO VARCHAR(100))
AS
BEGIN
    INSERT INTO FERIADOS (DIA_FERIADO, DESCRIPCION_FERIADO)
		VALUES (@DIA_FERIADO, @DESCRIPCION_FERIADO)
END

GO

--LEER 
CREATE OR ALTER PROCEDURE LEER_FERIADO(@COD_FERIADO INT)
AS
BEGIN
    SELECT COD_FERIADO, DIA_FERIADO, DESCRIPCION_FERIADO
    FROM FERIADOS
	WHERE COD_FERIADO = @COD_FERIADO
END
GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_FERIADO(@COD_FERIADO INT,
											 @DIA_FERIADO DATE,
											 @DESCRIPCION_FERIADO VARCHAR(100))
AS
BEGIN
    UPDATE FERIADOS
    SET DIA_FERIADO = @DIA_FERIADO, DESCRIPCION_FERIADO = @DESCRIPCION_FERIADO
    WHERE COD_FERIADO = @COD_FERIADO
END

GO

--BORRAR
CREATE OR ALTER PROCEDURE BORRAR_FERIADO(@COD_FERIADO INT)
AS
BEGIN
   DELETE FROM FERIADOS WHERE COD_FERIADO = @COD_FERIADO 
END

GO

--CRUD MATERIAS_ABIERTAS

CREATE OR ALTER PROCEDURE INSERTAR_MATERIAS_ABIERTAS(@COD_MATERIA_CARRERA INT,
									                 @COD_LABORATORIO INT,
										             @COD_PROFESOR INT,
										             @COSTO DECIMAL(10,2),
										             @GRUPO TINYINT,
										             @ESPACIO TINYINT,
													 @FECHA_INICIO DATE,
										             @DESCUENTO_M DECIMAL(10,2))
AS
BEGIN
    INSERT INTO MATERIAS_ABIERTAS(COD_MATERIA_CARRERA,COD_LABORATORIO,COD_PROFESOR,COSTO,GRUPO,ESPACIO,FECHA_INICIO,DESCUENTO_M)
		VALUES (@COD_MATERIA_CARRERA, @COD_LABORATORIO,@COD_PROFESOR,@COSTO,@GRUPO,@ESPACIO,@FECHA_INICIO,@DESCUENTO_M)
END

GO  

-- LEER
CREATE OR ALTER PROCEDURE LEER_MATERIA_ABIERTA(@COD_MATERIAS_ABIERTAS INT)
AS
BEGIN
    SELECT * FROM MATERIAS_ABIERTAS WHERE COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS
END
GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_MATERIAS_ABIERTAS(@COD_MATERIAS_ABIERTAS INT,
													   @COD_MATERIA_CARRERA INT,
									                   @COD_LABORATORIO INT,
										               @COD_PROFESOR INT,
										               @COSTO DECIMAL(10,2),
										               @GRUPO TINYINT,
										               @ESPACIO TINYINT,
										               @FECHA_FINAL DATE,
										               @DESCUENTO_M DECIMAL(10,2))
AS
BEGIN
    UPDATE MATERIAS_ABIERTAS 
    SET COD_MATERIA_CARRERA = @COD_MATERIA_CARRERA, COD_LABORATORIO = @COD_LABORATORIO, COD_PROFESOR = @COD_PROFESOR, COSTO = @COSTO, GRUPO = @GRUPO, ESPACIO = @ESPACIO, FECHA_FINAL = @FECHA_FINAL, DESCUENTO_M = @DESCUENTO_M
    WHERE COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS
END
GO
--BORRAR
CREATE OR ALTER PROCEDURE ELIMINAR_MATERIA_ABIERTA(@COD_MATERIAS_ABIERTAS INT)
AS
BEGIN
    DELETE FROM MATERIAS_ABIERTAS WHERE COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS
END
GO

--CRUD DETALLE_MATRICULAS

--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_DETALLE_MATRICULA(@NUM_RECIBO INT, 
											@COD_MATERIAS_ABIERTAS INT, 
											@PORC_DESCUENTO DECIMAL(4,2),
											@ESTADO_D VARCHAR(3))
AS
BEGIN
    INSERT INTO DETALLE_MATRICULA (NUM_RECIBO, COD_MATERIAS_ABIERTAS, PORC_DESCUENTO, ESTADO_D)
		VALUES (@NUM_RECIBO, @COD_MATERIAS_ABIERTAS, @PORC_DESCUENTO, @ESTADO_D)
END
GO

--LEER

CREATE OR ALTER PROCEDURE OBTENER_DETALLES_MATRICULA(@NUM_RECIBO INT)
AS
BEGIN
    SELECT *FROM DETALLES_MATRICULA WHERE NUM_RECIBO=@NUM_RECIBO
END
GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_DETALLE_MATRICULA(@NUM_RECIBO INT, 
													   @COD_MATERIAS_ABIERTAS INT, 
													   @PORC_DESCUENTO DECIMAL(4,2),
													   @ESTADO_D VARCHAR(3))
AS
BEGIN
    UPDATE DETALLE_MATRICULA
    SET COD_MATERIAS_ABIERTAS = @COD_MATERIAS_ABIERTAS, PORC_DESCUENTO = @PORC_DESCUENTO, ESTADO_D = @ESTADO_D
	WHERE NUM_RECIBO = @NUM_RECIBO
END
GO

--BORRAR

CREATE OR ALTER PROCEDURE ELIMINAR_DETALLE_MATRICULA(@NUM_RECIBO INT)   
AS
BEGIN
    DELETE FROM DETALLE_MATRICULA
    WHERE NUM_RECIBO = @NUM_RECIBO 
END
GO

--CRUD MATRICULAS

--INSERTAR 
CREATE OR ALTER PROCEDURE INSERTAR_MATRICULA(@CARNET VARCHAR(10),
											 @ESTADO VARCHAR(3),
											 @USUARIO_MATRICULA VARCHAR(20),
											 @OBSERVACIONES_MATRICULA VARCHAR(250),
											 @TOTAL DECIMAL(10,2),
										     @DESCUENTO_MAT DECIMAL(10,2))
AS
BEGIN
    INSERT INTO MATRICULAS (CARNET, ESTADO, USUARIO_MATRICULA, OBSERVACIONES_MATRICULA, FECHA, TOTAL, DESCUENTO_MAT)
		VALUES (@CARNET, @ESTADO, @USUARIO_MATRICULA, @OBSERVACIONES_MATRICULA, GETDATE(), @TOTAL, @DESCUENTO_MAT)
END
GO

--PROCEDIMIENTO PARA ACTUALIZAR UNA FILA EXISTENTE
CREATE OR ALTER PROCEDURE ACTUALIZAR_MATRICULA(@NUM_RECIBO INT,
									  @CARNET VARCHAR(10),
									  @ESTADO VARCHAR(3),
								      @USUARIO_MATRICULA VARCHAR(20),
									  @OBSERVACIONES_MATRICULA VARCHAR(250),
									  @TOTAL DECIMAL(10,2),
									  @DESCUENTO_MAT DECIMAL(10,2))
AS
BEGIN
    UPDATE MATRICULAS
    SET CARNET = @CARNET, ESTADO = @ESTADO, USUARIO_MATRICULA = @USUARIO_MATRICULA, 
        OBSERVACIONES_MATRICULA = @OBSERVACIONES_MATRICULA, TOTAL = @TOTAL, DESCUENTO_MAT = @DESCUENTO_MAT
    WHERE NUM_RECIBO = @NUM_RECIBO
END
GO

--ELIMINAR
CREATE OR ALTER PROCEDURE ELIMINAR_MATRICULA(@NUM_RECIBO INT)
AS
BEGIN
    DELETE FROM MATRICULAS WHERE NUM_RECIBO = @NUM_RECIBO
END
GO

--LEER
CREATE OR ALTER PROCEDURE OBTENER_MATRICULAS(@NUM_RECIBO INT)
AS
BEGIN
    SELECT * FROM MATRICULAS WHERE NUM_RECIBO=@NUM_RECIBO
END
GO

--CRUD CERTIFICADOS
--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_CERTIFICADO(@COD_CERTIFICADO VARCHAR(30),
									  @NOMBRE_CERTIFICADO VARCHAR(150))
AS
BEGIN
    INSERT INTO CERTIFICADOS (COD_CERTIFICADO, NOMBRE_CERTIFICADO)
		VALUES (@COD_CERTIFICADO, @NOMBRE_CERTIFICADO)
END
GO

--LEER
CREATE OR ALTER PROCEDURE OBTENER_CERTIFICADOS(@COD_CERTIFICADO VARCHAR(30))
AS
BEGIN
    SELECT * FROM CERTIFICADOS WHERE COD_CERTIFICADO=@COD_CERTIFICADO
END
GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_CERTIFICADO(@COD_CERTIFICADO VARCHAR(30),
										@NOMBRE_CERTIFICADO VARCHAR(150))
AS
BEGIN
    UPDATE CERTIFICADOS
    SET NOMBRE_CERTIFICADO = @NOMBRE_CERTIFICADO
    WHERE COD_CERTIFICADO = @COD_CERTIFICADO
END
GO

--ELIMINAR
CREATE OR ALTER PROCEDURE ELIMINAR_CERTIFICADO(@COD_CERTIFICADO VARCHAR(30))
AS
BEGIN
    DELETE FROM CERTIFICADOS WHERE COD_CERTIFICADO = @COD_CERTIFICADO
END
GO 

--CRUD CERTIFICADOS_PROFESORES
--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_CERTIFICADOS_PROFESORES(@COD_CERTIFICADO VARCHAR(30),
														   @COD_PROFESOR INT)
AS
BEGIN
    INSERT INTO CERTIFICADOS_PROFESORES (COD_CERTIFICADO, COD_PROFESOR)
		VALUES (@COD_CERTIFICADO, @COD_PROFESOR)
END
GO

--LEER
CREATE OR ALTER PROCEDURE OBTENER_CERTIFICADOS_PROFESORES(@COD_CERTIFICADO VARCHAR(30))
AS
BEGIN
    SELECT * FROM CERTIFICADOS_PROFESORES WHERE COD_CERTIFICADO=@COD_CERTIFICADO
END
GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_CERTIFICADOS_PROFESORES(@COD_CERTIFICADO VARCHAR(30),
															 @COD_PROFESOR INT)
AS
BEGIN
    UPDATE CERTIFICADOS_PROFESORES
    SET COD_CERTIFICADO = @COD_CERTIFICADO, COD_PROFESOR=@COD_PROFESOR
    WHERE COD_CERTIFICADO = @COD_CERTIFICADO
END
GO

--ELIMINAR
CREATE OR ALTER PROCEDURE ELIMINAR_CERTIFICADOS_PROFESORES(@COD_CERTIFICADO VARCHAR(30))
AS
BEGIN
    DELETE FROM CERTIFICADOS_PROFESORES WHERE COD_CERTIFICADO = @COD_CERTIFICADO
END
GO 

--CRUD PAGOS
--INSERTAR
CREATE OR ALTER PROCEDURE INSERTAR_PAGOS(@ID_PAGO INT,
										 @NUM_RECIBO INT,
										 @MONTO DECIMAL(10,2),
										 @DETALLE_PAGO VARCHAR(100))
AS
BEGIN
    INSERT INTO PAGOS(ID_PAGO,NUM_RECIBO,MONTO_PAGAR,DETALLE_PAGO)
		VALUES (@ID_PAGO, @NUM_RECIBO,@MONTO,@DETALLE_PAGO)
END
GO

--LEER
CREATE OR ALTER PROCEDURE OBTENER_PAGOS(@ID_PAGO INT)
AS
BEGIN
    SELECT * FROM PAGOS WHERE ID_PAGO=@ID_PAGO
END
GO

--ACTUALIZAR
CREATE OR ALTER PROCEDURE ACTUALIZAR_PAGOS(@NUM_RECIBO INT,
										   @MONTO DECIMAL(10,2),
										   @DETALLE_PAGO VARCHAR(100))
AS
BEGIN
    UPDATE PAGOS
    SET NUM_RECIBO=@NUM_RECIBO,MONTO_PAGAR=@MONTO, DETALLE_PAGO=@DETALLE_PAGO
    WHERE NUM_RECIBO = @NUM_RECIBO
END
GO

--ELIMINAR
CREATE OR ALTER PROCEDURE ELIMINAR_PAGOS(@NUM_RECIBO INT)
AS
BEGIN
    DELETE FROM PAGOS WHERE NUM_RECIBO = @NUM_RECIBO
END
GO